### ISSUE TITLE
Cody: New text categories

### ISSUE THREAD

**Issue by lweakly** [CDRH/data_cody#28]
We have three new categories of texts: Government Documents, Life Writing, and Pamphlets. Please add these to the texts page.

**Comment by karindalziel** [comment]
@lweakly please add sentences for the three new types. HEre's what we have for current types:

Correspondence

Letters written to and from William F. "Buffalo Bill" Cody and his numerous business and personal correspondents throughout his adult life.

Books

Full-text digital editions of key published works featuring William F. "Buffalo Bill" Cody. Titles include autobiographies, biographies, western Americana, and children's literature.

Newspapers

William F. Cody himself, The Buffalo Bill Combination and Buffalo Bill's Wild West appeared in numerous newspaper articles from 1870 to his death in 1917.

Periodicals

A comprehensive collection of popular press articles either on topics related to Cody or written by Cody himself for the mass market.

Records

Contents include business and legal records relating to both Buffalo Bill's Wild West and Cody's personal life.

**Comment by lweakly** [comment]
How about this?

Government Documents
Official documents from all levels of government concerning William F. Cody and the people and places surrounding him. 

Life Writing
Biographies, autobiographies, and personal narratives written by people associated with William F. Cody, generally unpublished manuscripts or typescripts.

Pamphlets
Various pamphlets and brochures concerning William F. Cody or on topics related to Cody.

**Comment by karindalziel** [comment]
These are up http://codyarchive.org/texts/
